### ISSUE TITLE
Category does not work when scheduled on a timer for repeating

### ISSUE THREAD

**Issue by ArvinB** [rentzsch/NSInvocation-blocks#1]
As the title says, the code did not work for me when I used it with an NSTimer set to repeat.

Instead I wrote the following which does work and I think is cleaner. Note: I have ARC ON.

NSObject Category Header:
@interface NSObject (CategoryNSObject)
- (void) associateValue:(id)value withKey:(NSString *)aKey;
- (id) associatedValueForKey:(NSString *)aKey;

@end
Implementation:
# import "Categories.h"
# import <objc/runtime.h>

@implementation NSObject (CategoryNSObject)
# pragma mark Associated Methods:
- (void) associateValue:(id)value withKey:(NSString *)aKey {
  
  objc_setAssociatedObject( self, (__bridge void *)aKey, value, OBJC_ASSOCIATION_RETAIN );
  }
- (id) associatedValueForKey:(NSString *)aKey {
  
  return objc_getAssociatedObject( self, (__bridge void *)aKey );
  }

@end

NSInvocation Category Header:

@interface NSInvocation (CategoryNSInvocation)
- (NSInvocation *) invocationWithTarget:(id)aTarget block:(void (^)(id target))block;
- (NSInvocation *) invocationWithSelector:(SEL)aSelector forTarget:(id)aTarget;
- (NSInvocation *) invocationWithSelector:(SEL)aSelector andObject:(__autoreleasing id)anObject forTarget:(id)aTarget;

@end

Implementation:
# import "Categories.h"

typedef void (^BlockInvocationBlock)(id target);
# pragma mark - Private Interface:

@interface BlockInvocation : NSObject
@property (readwrite, nonatomic, copy) BlockInvocationBlock block;
@end
# pragma mark - Invocation Container:

@implementation BlockInvocation

@synthesize block;
- (id) initWithBlock:(BlockInvocationBlock)aBlock {
  
  if ( (self = [super init]) ) {
  
  ```
  self.block = aBlock;
  ```
  
  } return self;
  }
- (BlockInvocation *) invocationWithBlock:(BlockInvocationBlock)aBlock {
  return [[self alloc] initWithBlock:aBlock];
  }
- (void) performWithTarget:(id)aTarget {
  self.block(aTarget);
  }

@end
# pragma mark Implementation:

@implementation NSInvocation (CategoryNSInvocation)
# pragma mark - Class Methods:
- (NSInvocation *) invocationWithTarget:(id)aTarget block:(void (^)(id target))block {
  
  BlockInvocation *blockInvocation = [BlockInvocation invocationWithBlock:block];
  NSInvocation *invocation = [NSInvocation invocationWithSelector:@selector(performWithTarget:) andObject:aTarget forTarget:blockInvocation];
  [invocation associateValue:blockInvocation withKey:@"BlockInvocation"];
  return invocation;
  }
- (NSInvocation *) invocationWithSelector:(SEL)aSelector forTarget:(id)aTarget {
  
  NSMethodSignature   *aSignature  = [aTarget methodSignatureForSelector:aSelector];
  NSInvocation        *aInvocation = [NSInvocation invocationWithMethodSignature:aSignature];
  [aInvocation setTarget:aTarget];
  [aInvocation setSelector:aSelector];
  return aInvocation;
  }
- (NSInvocation *) invocationWithSelector:(SEL)aSelector andObject:(__autoreleasing id)anObject forTarget:(id)aTarget {
  
  NSInvocation *aInvocation = [NSInvocation invocationWithSelector:aSelector 
                                                         forTarget:aTarget];
  [aInvocation setArgument:&anObject atIndex:2];
  return aInvocation;
  }

@end

So this avoids the abstract class of NSProxy and seems a bit more objective-c "like" ;-)

Hope this helps.

**Comment by krzysztofzablocki** [comment]
I like the idea, the original code might suggest that block syntax supports multiple calls but it will only execute latest one, this makes it support multiple ones and simplifies category code (it would be more code to add support for that with NSInvocation and NSProxy stuff).

One thing about the code, association key is matched on pointer basis not on object equality, although your code might work in this case as you use it to force lifetime of blockInvocation and never request it back, the category for associations is bad and it's suggesting equality comparison not pointer based one. 

If you want to have NSString equality comparable keys for associated objects in your category that would be pretty simple to implement, you could just store keys in dictionary Dict[Key] = Key, then on request you use Dict[Key] to get key for association.
